

### Filing Date Search ###

COURT_DESCRIPTIONS = [
    'Supreme Court', 'Eastern Appellate', 'Southern Appellate', 'Western Appellate',
    'Fine Collection Center', '1st Judicial Circuit (Clark, Schuyler & Scotland Counties)',
    '2nd Judicial Circuit (Adair, Knox & Lewis Counties)',
    '3rd Judicial Circuit (Grundy, Harrison, Mercer & Putnam Counties)',
    '4th Judicial Circuit (Atchison, Gentry, Holt, Nodaway & Worth Counties)',
    '5th Judicial Circuit (Andrew & Buchanan Counties)', '6th Judicial Circuit (Platte County)',
    '7th Judicial Circuit (Clay County)', '8th Judicial Circuit (Carroll & Ray Counties)',
    '9th Judicial Circuit (Sullivan, Linn & Chariton Counties)',
    '10th Judicial Circuit (Marion, Monroe & Ralls Counties)',
    '11th Judicial Circuit (St. Charles County)',
    '12th Judicial Circuit (Audrain, Montgomery & Warren Counties)',
    '13th Judicial Circuit (Boone & Callaway Counties)',
    '14th Judicial Circuit (Randolph & Howard Counties)',
    '15th Judicial Circuit (Saline & Lafayette Counties)', '16th Judicial Circuit (Jackson County)',
    '17th Judicial Circuit (Cass & Johnson Counties)', '18th Judicial Circuit (Cooper & Pettis Counties)',
    '19th Judicial Circuit (Cole County)', '20th Judicial Circuit (Franklin, Gasconade & Osage Counties)',
    '21st Judicial Circuit (St. Louis County)', '22nd Judicial Circuit (City of St. Louis)',
    '23rd Judicial Circuit (Jefferson County)',
    '24th Judicial Circuit (Madison, Ste. Genevieve, St.  Francois & Washington Counties)',
    '25th Judicial Circuit (Maries, Phelps, Pulaski & Texas Counties)',
    '26th Judicial Circuit (Camden, Laclede, Miller, Morgan & Moniteau Counties)',
    '27th Judicial Circuit (Bates, Henry & St. Clair Counties)',
    '28th Judicial Circuit (Barton, Cedar, Dade & Vernon Counties)',
    '29th Judicial Circuit (Jasper County)',
    '30th Judicial Circuit (Benton, Dallas, Hickory, Polk & Webster Counties)',
    '31st Judicial Circuit (Greene County)',
    '32nd Judicial Circuit ( Bollinger, Cape Girardeau & Perry Counties)',
    '33rd Judicial Circuit (Mississippi & Scott Counties)',
    '34th Judicial Circuit (New Madrid & Pemiscot Counties)',
    '35th Judicial Circuit (Dunklin & Stoddard Counties)', '36th Judicial Circuit (Butler & Ripley Counties)',
    '37th Judicial Circuit (Carter, Howell, Oregon & Shannon Counties)',
    '38th Judicial Circuit (Christian County)', '39th Judicial Circuit (Barry, Lawrence & Stone Counties)',
    '40th Judicial Circuit (Newton & McDonald Counties)', '41st Judicial Circuit (Macon & Shelby Counties)',
    '42nd Judicial Circuit (Dent, Crawford, Iron, Reynolds & Wayne Counties)',
    '43rd Judicial Circuit (DeKalb, Daviess, Clinton, Caldwell & Livingston Counties)',
    '44th Judicial Circuit (Douglas, Ozark & Wright Counties)',
    '45th Judicial Circuit (Lincoln & Pike Counties)', '46th Judicial Circuit (Taney County)'
]

COURT_IDS = {
    'Supreme Court': 'OSCDB0024_SUP',
    'Eastern Appellate': 'SMPDB0005_EAP',
    'Southern Appellate': 'SMPDB0001_SAP',
    'Western Appellate': 'SMPDB0001_WAP',
    'Fine Collection Center': 'FCC',
    '1st Judicial Circuit (Clark, Schuyler & Scotland Counties)': 'SMPDB0004_CT01',
    '2nd Judicial Circuit (Adair, Knox & Lewis Counties)': 'SMPDB0004_CT02',
    '3rd Judicial Circuit (Grundy, Harrison, Mercer & Putnam Counties)': 'SMPDB0001_CT03',
    '4th Judicial Circuit (Atchison, Gentry, Holt, Nodaway & Worth Counties)': 'SMPDB0001_CT04',
    '5th Judicial Circuit (Andrew & Buchanan Counties)': 'CT05',
    '6th Judicial Circuit (Platte County)': 'SMPDB0001_CT06',
    '7th Judicial Circuit (Clay County)': 'SMPDB0001_CT07',
    '8th Judicial Circuit (Carroll & Ray Counties)': 'CT08',
    '9th Judicial Circuit (Sullivan, Linn & Chariton Counties)': 'SMPDB0001_CT09',
    '10th Judicial Circuit (Marion, Monroe & Ralls Counties)': 'SMPDB0004_CT10',
    '11th Judicial Circuit (St. Charles County)': 'CT11',
    '12th Judicial Circuit (Audrain, Montgomery & Warren Counties)': 'CT12',
    '13th Judicial Circuit (Boone & Callaway Counties)': 'CT13',
    '14th Judicial Circuit (Randolph & Howard Counties)': 'SMPDB0001_CT14',
    '15th Judicial Circuit (Saline & Lafayette Counties)': 'SMPDB0001_CT15',
    '16th Judicial Circuit (Jackson County)': 'CT16',
    '17th Judicial Circuit (Cass & Johnson Counties)': 'CT17',
    '18th Judicial Circuit (Cooper & Pettis Counties)': 'CT18',
    '19th Judicial Circuit (Cole County)': 'SMPDB0004_CT19',
    '20th Judicial Circuit (Franklin, Gasconade & Osage Counties)': 'SMPDB0004_CT20',
    '21st Judicial Circuit (St. Louis County)': 'CT21',
    '22nd Judicial Circuit (City of St. Louis)': 'CT22',
    '23rd Judicial Circuit (Jefferson County)': 'CT23',
    '24th Judicial Circuit (Madison, Ste. Genevieve, St.  Francois & Washington Counties)': 'SMPDB0005_CT24',
    '25th Judicial Circuit (Maries, Phelps, Pulaski & Texas Counties)': 'SMPDB0005_CT25',
    '26th Judicial Circuit (Camden, Laclede, Miller, Morgan & Moniteau Counties)': 'SMPDB0004_CT26',
    '27th Judicial Circuit (Bates, Henry & St. Clair Counties)': 'SMPDB0005_CT27',
    '28th Judicial Circuit (Barton, Cedar, Dade & Vernon Counties)': 'SMPDB0004_CT28',
    '29th Judicial Circuit (Jasper County)': 'SMPDB0001_CT29',
    '30th Judicial Circuit (Benton, Dallas, Hickory, Polk & Webster Counties)': 'SMPDB0005_CT30',
    '31st Judicial Circuit (Greene County)': 'CT31',
    '32nd Judicial Circuit ( Bollinger, Cape Girardeau & Perry Counties)': 'SMPDB0001_CT32',
    '33rd Judicial Circuit (Mississippi & Scott Counties)': 'SMPDB0005_CT33',
    '34th Judicial Circuit (New Madrid & Pemiscot Counties)': 'SMPDB0005_CT34',
    '35th Judicial Circuit (Dunklin & Stoddard Counties)': 'SMPDB0001_CT35',
    '36th Judicial Circuit (Butler & Ripley Counties)': 'SMPDB0004_CT36',
    '37th Judicial Circuit (Carter, Howell, Oregon & Shannon Counties)': 'SMPDB0005_CT37',
    '38th Judicial Circuit (Christian County)': 'CT38',
    '39th Judicial Circuit (Barry, Lawrence & Stone Counties)': 'CT39',
    '40th Judicial Circuit (Newton & McDonald Counties)': 'SMPDB0001_CT40',
    '41st Judicial Circuit (Macon & Shelby Counties)': 'SMPDB0004_CT41',
    '42nd Judicial Circuit (Dent, Crawford, Iron, Reynolds & Wayne Counties)': 'SMPDB0005_CT42',
    '43rd Judicial Circuit (DeKalb, Daviess, Clinton, Caldwell & Livingston Counties)': 'SMPDB0005_CT43',
    '44th Judicial Circuit (Douglas, Ozark & Wright Counties)': 'SMPDB0005_CT44',
    '45th Judicial Circuit (Lincoln & Pike Counties)': 'SMPDB0005_CT45',
    '46th Judicial Circuit (Taney County)': 'CT46'
}

COUNTY_CODES = {
    'Clark': 'CLK', 'Scotland': 'SLD', 'Schuyler': 'SYR', 'Adair': 'ADR', 'Knox': 'KNX',
    'Lewis': 'LEW', 'Grundy': 'GRU', 'Harrison': 'HAR', 'Mercer': 'MER', 'Putnam': 'PUT', 'Atchison': 'ATN',
    'Gentry': 'GEN', 'Holt': 'HOL', 'Nodaway': 'NDY', 'Worth': 'WOR', 'Andrew': 'ADW', 'Buchanan': 'BUC',
    'Platte': 'PLA', 'Clay': 'CLY', 'Carroll': 'CRL', 'Ray': 'RAY', 'Chariton': 'CHN', 'Linn': 'LIN',
    'Sulivan': 'SUL', 'Monroe': 'MNR', 'Marion': 'MRN', 'Ralls': 'RAL', 'St. Charles': 'SCH', 'Audrain': 'AUD',
    'Montgomery': 'MTY', 'Warren': 'WRN', 'Boone': 'BNE', 'Callaway': 'CWY', 'Howard': 'HWD', 'Randolph': 'RAN',
    'Lafayette': 'LAF', 'Saline': 'SAL', 'Jackson': 'JAK', 'Cass': 'CAS', 'Johnson': 'JON', 'Cooper': 'CPR',
    'Pettis': 'PET', 'Cole': 'COL', 'Franklin': 'FKN', 'Gasconade': 'GAS', 'Osage': 'OSG', 'St. Louis County': 'SLC',
    'The City of St. Louis': 'STL', 'Jefferson': 'JEF', 'Madison': 'MAD', 'St. Francois': 'SFR', 'Ste. Genevieve': 'SGE',
    'Washington': 'WAS', 'Maries County': 'MRS', 'Phelps County': 'PHE', 'Pulaski': 'PUL', 'Texas': 'TEX',
    'Camden': 'CAM', 'Laclede': 'LAC', 'Miller': 'MIL', 'Morgan': 'MOR', 'Moniteau': 'MTU', 'Bates': 'BAT',
    'Henry': 'HEN', 'St. Clair': 'SCL', 'Barton': 'BAR', 'Cedar': 'CDR', 'Dade': 'DAD', 'Vernon': 'VER', 'Jasper': 'JAS',
    'Benton': 'BEN', 'Dallas': 'DAL', 'Hickory': 'HIK', 'Polk': 'POL', 'Webster': 'WEB', 'Greene': 'GRE',
    'Bollinger': 'BOL', 'Cape Girardeau': 'CPG', 'Perry': 'PER', 'Mississippi': 'MIS', 'Scott': 'SCT', 'New Madrid': 'NMD',
    'Pemiscot': 'PEM', 'Dunklin': 'DUN', 'Stoddard': 'SDD', 'Butler': 'BTR', 'Ripley': 'RIP', 'Carter': 'CTR',
    'Howell': 'HWL', 'Oregon': 'ORE', 'Shannon': 'SHA', 'Christian': 'CTN', 'Barry': 'BRY', 'Lawrence': 'LAW',
    'Stone': 'STN', 'McDonald': 'MCD', 'Newton': 'NWT', 'Macon': 'MAC', 'Shelby': 'SBY', 'Crawford': 'CFD', 'Dent': 'DEN',
    'Iron': 'IRN', 'Reynolds': 'REY', 'Wayne': 'WAY', 'Caldwell': 'CDL', 'Clinton': 'CLN', 'Daviess': 'DAV', 'DeKalb': 'DEK',
    'Livingston': 'LIV', 'Douglas': 'DGS', 'Ozark': 'OZK', 'Wright': 'WRI', 'Lincoln': 'LCN', 'Pike': 'PIK', 'Taney': 'TAN'
}

COURT_COUNTIES = {
    '1st Judicial Circuit (Clark, Schuyler & Scotland Counties)': ['Clark',
                                                                'Scotland',
                                                                'Schuyler'],
    '2nd Judicial Circuit (Adair, Knox & Lewis Counties)': ['Adair',
                                                            'Knox',
                                                            'Lewis'],
    '3rd Judicial Circuit (Grundy, Harrison, Mercer & Putnam Counties)': ['Grundy',
                                                                        'Harrison',
                                                                        'Mercer',
                                                                        'Putnam'],
    '4th Judicial Circuit (Atchison, Gentry, Holt, Nodaway & Worth Counties)': ['Atchison',
                                                                                'Gentry',
                                                                                'Holt',
                                                                                'Nodaway',
                                                                                'Worth'],
    '5th Judicial Circuit (Andrew & Buchanan Counties)': ['Andrew', 'Buchanan'],
    '6th Judicial Circuit (Platte County)': ['Platte'],
    '7th Judicial Circuit (Clay County)': ['Clay'],
    '8th Judicial Circuit (Carroll & Ray Counties)': ['Carroll', 'Ray'],
    '9th Judicial Circuit (Sullivan, Linn & Chariton Counties)': ['Chariton',
                                                                'Linn',
                                                                'Sulivan'],
    '10th Judicial Circuit (Marion, Monroe & Ralls Counties)': ['Monroe',
                                                                'Marion',
                                                                'Ralls'],
    '11th Judicial Circuit (St. Charles County)': ['St. Charles'],
    '12th Judicial Circuit (Audrain, Montgomery & Warren Counties)': ['Audrain',
                                                                    'Montgomery',
                                                                    'Warren'],
    '13th Judicial Circuit (Boone & Callaway Counties)': ['Boone', 'Callaway'],
    '14th Judicial Circuit (Randolph & Howard Counties)': ['Howard', 'Randolph'],
    '15th Judicial Circuit (Saline & Lafayette Counties)': ['Lafayette', 'Saline'],
    '16th Judicial Circuit (Jackson County)': ['Jackson'],
    '17th Judicial Circuit (Cass & Johnson Counties)': ['Cass', 'Johnson'],
    '18th Judicial Circuit (Cooper & Pettis Counties)': ['Cooper', 'Pettis'],
    '19th Judicial Circuit (Cole County)': ['Cole'],
    '20th Judicial Circuit (Franklin, Gasconade & Osage Counties)': ['Franklin',
                                                                    'Gasconade',
                                                                    'Osage'],
    '21st Judicial Circuit (St. Louis County)': ['St. Louis County'],
    '22nd Judicial Circuit (City of St. Louis)': ['The City of St. Louis'],
    '23rd Judicial Circuit (Jefferson County)': ['Jefferson'],
    '24th Judicial Circuit (Madison, Ste. Genevieve, St.  Francois & Washington Counties)': ['Madison',
                                                                                            'St. '
                                                                                            'Francois',
                                                                                            'Ste. '
                                                                                            'Genevieve',
                                                                                            'Washington'],
    '25th Judicial Circuit (Maries, Phelps, Pulaski & Texas Counties)': ['Maries '
                                                                        'County',
                                                                        'Phelps '
                                                                        'County',
                                                                        'Pulaski',
                                                                        'Texas'],
    '26th Judicial Circuit (Camden, Laclede, Miller, Morgan & Moniteau Counties)': ['Camden',
                                                                                    'Laclede',
                                                                                    'Miller',
                                                                                    'Morgan',
                                                                                    'Moniteau'],
    '27th Judicial Circuit (Bates, Henry & St. Clair Counties)': ['Bates',
                                                                'Henry',
                                                                'St. Clair'],
    '28th Judicial Circuit (Barton, Cedar, Dade & Vernon Counties)': ['Barton',
                                                                    'Cedar',
                                                                    'Dade',
                                                                    'Vernon'],
    '29th Judicial Circuit (Jasper County)': ['Jasper'],
    '30th Judicial Circuit (Benton, Dallas, Hickory, Polk & Webster Counties)': ['Benton',
                                                                                'Dallas',
                                                                                'Hickory',
                                                                                'Polk',
                                                                                'Webster'],
    '31st Judicial Circuit (Greene County)': ['Greene'],
    '32nd Judicial Circuit ( Bollinger, Cape Girardeau & Perry Counties)': ['Bollinger',
                                                                            'Cape '
                                                                            'Girardeau',
                                                                            'Perry'],
    '33rd Judicial Circuit (Mississippi & Scott Counties)': ['Mississippi',
                                                            'Scott'],
    '34th Judicial Circuit (New Madrid & Pemiscot Counties)': ['New Madrid',
                                                            'Pemiscot'],
    '35th Judicial Circuit (Dunklin & Stoddard Counties)': ['Dunklin', 'Stoddard'],
    '36th Judicial Circuit (Butler & Ripley Counties)': ['Butler', 'Ripley'],
    '37th Judicial Circuit (Carter, Howell, Oregon & Shannon Counties)': ['Carter',
                                                                        'Howell',
                                                                        'Oregon',
                                                                        'Shannon'],
    '38th Judicial Circuit (Christian County)': ['Christian'],
    '39th Judicial Circuit (Barry, Lawrence & Stone Counties)': ['Barry',
                                                                'Lawrence',
                                                                'Stone'],
    '40th Judicial Circuit (Newton & McDonald Counties)': ['McDonald', 'Newton'],
    '41st Judicial Circuit (Macon & Shelby Counties)': ['Macon', 'Shelby'],
    '42nd Judicial Circuit (Dent, Crawford, Iron, Reynolds & Wayne Counties)': ['Crawford',
                                                                                'Dent',
                                                                                'Iron',
                                                                                'Reynolds',
                                                                                'Wayne'],
    '43rd Judicial Circuit (DeKalb, Daviess, Clinton, Caldwell & Livingston Counties)': ['Caldwell',
                                                                                        'Clinton',
                                                                                        'Daviess',
                                                                                        'DeKalb',
                                                                                        'Livingston'],
    '44th Judicial Circuit (Douglas, Ozark & Wright Counties)': ['Douglas',
                                                                'Ozark',
                                                                'Wright'],
    '45th Judicial Circuit (Lincoln & Pike Counties)': ['Lincoln', 'Pike'],
    '46th Judicial Circuit (Taney County)': ['Taney']
}

LOCATION_CODES = {
    'Adrain Municipal': '4P',
    'Airport Drive Municipal': ']L',
    'Albany Municipal': '5Y',
    'Allenville Municipal': ']O',
    'Alma Municipal': 'AV',
    'Altamont Municipal': '!O',
    'Alton Municipal': '(I',
    'Anderson Municipal Court': ')Z',
    'Annapolis Municipal': 'IA',
    'Anniston Municipal Court': ']Q',
    'Appleton City Municipal': '5:',
    'Arbyrd Municipal': '4B',
    'Arcadia Municipal': '7J',
    'Archie Municipal': '*D',
    'Arnold Municipal': '83',
    'Ash Grove Municipal': '2U',
    'Ashland Municipal Division': '[A',
    'Assoc Crim/Probate Christian': 'N8',
    'Assoc Crim/Probate Div Taney': 'N9',
    'Associate Civil Div Christian': 'N7',
    'Associate Civil Division Taney': 'D2',
    'Associate Civil/Small Claim': 'B9',
    'Associate Div Bates': 'T1',
    'Associate Division': 'P3',
    'Associate Division (Jackson)': 'G9',
    'Associate Division 3': 'D7',
    'Associate Division Adair': 'H4',
    'Associate Division Audrain': 'U1',
    'Associate Division Barry': 'R5',
    'Associate Division Daviess': 'V1',
    'Associate Division DeKalb': 'K4',
    'Associate Division Douglas': 'U4',
    'Associate Division IV': 'D4',
    'Associate Division Knox': 'K3',
    'Associate Division Lawrence': 'L2',
    'Associate Division Livingston': 'L4',
    'Associate Division Moniteau': 'M5',
    'Associate Division Morgan': 'M6',
    'Associate Division Ozark': 'K5',
    'Associate Division V': 'D5',
    'Associate Division VI': 'E5',
    'Associate Division VII': 'E1',
    'Associate Division Wright': 'W1',
    'Associate Probate Division': 'G8',
    'Associate/Circuit Divisions': 'L6',
    'Atlanta Municipal': 'MB',
    'Augusta Municipal': 'W=',
    'Aurora Municipal Court': '7E',
    'Auxvasse Municipal': '3U',
    'Ava Municipal': '68',
    'Avondale Municipal': '*5',
    'Ballwin Municipal': '75',
    'Barnard Municipal': 'NQ',
    'Barry': 'BR',
    'Bates City Municipal': '[H',
    'Bates County Circuit Court': 'BS',
    'Battlefield Municipal': '7K',
    'Bel-Nor Municipal': '[N',
    'Bel-Ridge Municipal Court': '[P',
    'Bell City Municipal': ']U',
    'Bella Villa Municipal Court': '@B',
    'Belle Municipal': 'BZ',
    'Bellefontaine Neighbors': '85',
    'Bellerive Acres Municipal': '+H',
    'Bellflower Municipal Court': 'A2',
    'Benton City Municipal Court': '4:',
    'Benton Municipal Court': '[2',
    'Berger Municipal Court': '+O',
    'Berkeley Municipal': 'L3',
    'Bethany Municipal': '?L',
    'Beverly Hills Municipal': 'A=',
    'Bevier Municipal': 'BV',
    'Big Lake Municipal': '!2',
    'Birch Tree Municipal': '7G',
    'Birmingham Municipal': '*6',
    'Black Jack Municipal': '[Q',
    'Blackburn Municipal': '2M',
    'Blackwater Municipal': 'BC',
    'Bland Municipal': 'BX',
    'Bogard Municipal': '!9',
    'Bolivar Municipal': 'BI',
    'Bonne Terre Municipal Court': '63',
    'Boonville Municipal Division': '3O',
    'Bosworth Municipal': '!A',
    'Bourbon Municipal Court': ')A',
    'Bowling Green Municipal': 'K:',
    'Branson Municipal': '5Q',
    'Branson West Municipal': '4J',
    'Brashear Municipal': 'BH',
    'Braymer Municipal': '8X',
    'Breckenridge Hills Municipal': '[R',
    'Breckenridge Municipal': '?4',
    'Brentwood Municipal': '37',
    'Bridgeton Municipal': '5R',
    'Bronaugh Municipal Court': ']H',
    'Brookfield Municipal': '6N',
    'Browning Municipal': ')W',
    'Bucklin Municipal': '2C',
    'Buffalo Municipal': ']M',
    'Bunceton Municipal': 'AY',
    'Bunker Municipal Court': ')B',
    'Burlington Junction Municipal': 'F:',
    'Butterfield Municipal': 'FB',
    'Byrnes Municipal': '2H',
    'Cabool Municipal': '6J',
    'Caldwell Circuit Court': 'CL',
    'Caldwell Municipal': '2V',
    'Caledonia Municipal': '!X',
    'Calhoun Municipal': '!K',
    'California Municipal Court': '(2',
    'Callao Municipal': '!Y',
    'Calverton Park Municipal': '[S',
    'Camden Circuit': 'CM',
    'Camden Municipal': 'KM',
    'Camden Point Municipal': '?P',
    'Camdenton Municipal': '74',
    'Cameron Municipal Court': '5U',
    'Campbell Municipal': '6G',
    'Canalou Municipal': 'LU',
    'Canton Municipal': '3D',
    'Carl Junction Municipal': 'OM',
    'Carnahan Courthouse': 'CB',
    'Carrollton Municipal': '9B',
    'Carterville Municipal': '(6',
    'Carthage Municipal': 'CX',
    'Caruthersville Municipal Court': '$K',
    'Cass Circuit': 'CA',
    'Cass County Ordinance Court': '@I',
    'Cassville Municipal Court': '9R',
    'Center Municipal': '*8',
    'Centerview Muncipal': '*E',
    'Centralia Municipal Division': '[B',
    'Champ Municipal': '6O',
    'Charlack Municipal Court': '[T',
    'Chesterfield Municipal Court': '[U',
    'Chilhowee Municipal': '*F',
    'Chillicothe Municipal': '?5',
    'Christian County Cir Ct Bldg': 'CV',
    'Christian Historic Courthouse': 'CQ',
    'Circuit Division': 'AF',
    'Circuit Division (Cape Girard)': 'CG',
    'Circuit Division (Carthage)': 'AP',
    'Circuit Division (Family Ct Justice Cntr)': 'B1',
    'Circuit Division (Independence)': 'B3',
    'Circuit Division (Jackson)': 'CJ',
    'Circuit Division (Joplin)': 'AO',
    'Circuit Division (Kansas City)': 'B2',
    'Circuit Division Audrain': 'AU',
    'City of Billings Municipal Court': '4U',
    'City of Clever Municipal Court': '8B',
    'City of St. Louis': 'ST',
    'City of Washington': '[L',
    'Clarence Municipal': '6K',
    'Clark Municipal': '5I',
    'Clarksburg Municipal Court': '(3',
    'Clarksdale Municipal': '?6',
    'Clarkson Valley Municipal': '87',
    'Clarksville Municipal': '3:',
    'Clay Circuit Court': 'CY',
    'Clayton Municipal Court': '47',
    'Clearmont Municipal': 'NB',
    'Cleveland Municipal': '*G',
    'Clinton Circuit Court': 'CN',
    'Clyde Municipal': 'NC',
    'Cole Camp Municipal': '2P',
    'Columbia Municipal': '6M',
    'Conception Junction Municipal': 'NE',
    'Conception Municipal': 'NF',
    'Concordia Municipal': '7D',
    'Conway Municipal': '*U',
    'Cool Valley Municipal': '[V',
    'Corder Municipal': '!G',
    'Cottleville Municipal': 'OT',
    'Country Club Hills': '5J',
    'Country Club Municipal': '!7',
    'Cowgill Municipal': '?7',
    'Craig Municipal': 'E:',
    'Crane Municipal Court': '4M',
    'Creighton Municipal': '*H',
    'Crestwood Municipal': '27',
    'Creve Coeur Municipal': 'M9',
    'Criminal Associate Division': 'E7',
    'Criminal Justice Center': 'CU',
    'Crocker Municipal': '8R',
    'Crystal City Municipal': '6Z',
    'Crystal Lake Park Municipal': '+J',
    'Crystal Lakes Municipal': 'L8',
    'Dardenne Prarie Municipal': 'DP',
    'Daviess Circuit Court': 'DV',
    'DeKalb Circuit Court': 'DK',
    'Dearborn Municipal': '2N',
    'Deepwater Municipal': '!L',
    'Dellwood Municipal': '[W',
    'Delta Municipal': ']P',
    'Dent Judicial Building': 'DZ',
    'Des Peres Municipal': '[X',
    'Desloge Municipal': '9Z',
    'Desoto Municipal': 'DC',
    'Dexter Municipal': '9H',
    'Diamond Municipal Court': ')5',
    'Div III & Probate': 'F9',
    'Dixon Municipal': '7U',
    'Doniphan Municipal Court': '*W',
    'Doolittle Municipal': '?I',
    'Douglas Circuit Court': 'DG',
    'Drexel Municipal': '*J',
    'Duquesne Municipal': 'DQ',
    'Eagleville Municipal': 'EG',
    'East Lynne Municipal': '*K',
    'Easton Buchanan Municipal': 'EA',
    'Edgar Springs Municipal': '+X',
    'Edgerton Municipal': '?Q',
    'Edina Municipal': 'G=',
    'Edmundson Muncipal Court': '99',
    'El Dorado Springs Municipal': 'ES',
    'Eldon Municipal Court': '(4',
    'Ellington Municipal Court': ')C',
    'Ellisville Municipal Court': '93',
    'Ellsinore Municipal': ')Q',
    'Elmo Municipal': 'NG',
    'Elsberry Municipal': '2J',
    'Eminence Municipal': '(O',
    'Emma Municipal': '!I',
    'Eolia Municipal': '34',
    'Essex Municipal': ']V',
    'Eureka Municipal': '95',
    'Everton Municipal Court': ']F',
    'Exeter Municipal': '73',
    'Fair Grove Municipal Court': '3S',
    'Fairfax Municipal': '9U',
    'Fairview Municipal': '8O',
    'Farber Municipal Court': '[7',
    'Farmington Municipal': '57',
    'Fayette Municipal': '62',
    'Fenton Municipal': '[Y',
    'Ferguson Municipal Court': '[Z',
    'Ferrelview Municipal': '8A',
    'Festus Municipal': 'FE',
    'Fisk Municipal Division': '*X',
    'Fleming Municipal': 'FL',
    'Flordell Hills Municipal': '79',
    'Florissant Municipal Court': 'N4',
    'Foley Municipal': '7N',
    'Fordland Municipal': 'FO',
    'Forest City Municipal': '*2',
    'Foristell Municipal': 'FT',
    'Forsyth Municipal': '2A',
    "Fountain N' Lakes": '?J',
    'Four Seasons Municipal Court': '9V',
    'Frankford Municipal': 'FD',
    'Franklin Co Municipal': 'FK',
    'Fredericktown Municipal': '9S',
    'Freeburg Municipal': ']6',
    'Freeman Municipal': '*L',
    'Freistatt Municipal Court': ']W',
    'Frontenac Municipal Court': '+K',
    'Fulton Municipal Court': '6P',
    'Gainsville Municipal Court': ')J',
    'Galena Municipal': '7X',
    'Gallatin Municipal': '!N',
    'Garden City Municipal': '4T',
    'Gasconade Municipal Court': '+E',
    'Gerald Municipal Court': '+F',
    'Gilman City Municipal': '6L',
    'Glasgow Municipal': '7Q',
    'Glen Echo Park Municipal': '@A',
    'Glenaire Municipal': '*7',
    'Glendale Municipal': ']2',
    'Golden City Municipal': ']C',
    'Goodman Municipal Court': '3M',
    'Gordonville Municipal': 'U=',
    'Graham Municipal': 'NH',
    'Granby Municipal Court': ')6',
    'Grandin Municipal': ')T',
    'Grandview Municipal': '64',
    'Grant City Municipal': ')M',
    'Grantwood Village Municipal': '8J',
    'Green City Municipal': ')S',
    'Greendale Municipal': '+L',
    'Greene County Ordinance Court': 'G:',
    'Greenfield Municipal': 'GF',
    'Greenridge Municipal': '!J',
    'Greentop Municipal': '@O',
    'Greenwood Municipal': '9W',
    'Guilford Municipal': 'NL',
    'Hale Municipal': '!C',
    'Hallsville Municipal Division': '5X',
    'Hanley Hills Municipal Court': ']3',
    'Hannibal Municipal Court': '$G',
    'Hardin Municipal': 'HA',
    'Hartville Municipal': '4F',
    'Hawk Point Municipal': '?K',
    'Hazelwood Municipal': 'HZ',
    'Henrietta Municipal': 'HR',
    'Henry County Circuit Court': 'HE',
    'Herculaneum Municipal': '9N',
    'Hermann Municipal': '4Y',
    'Higginsville Municipal Court': '8W',
    'High Hill Municipal Court': '[I',
    'Highlandville Municipal': 'HV',
    'Hillsboro Municipal': 'HB',
    'Hillsdale Municipal': '+M',
    'Holden Municipal': '*M',
    'Holt Municipal': '6Q',
    'Holts Summit Municipal Court': '9=',
    'Homestead Municipal': '!F',
    'Hopkins Municipal': '!5',
    'Hornersville Municipal': '(Y',
    'Houston Lake Municipal': '?R',
    'Houston Municipal': '8K',
    'Houstonia Municipal': 'BD',
    'Hughesville Municipal': 'BF',
    'Humansville Municipal': 'HU',
    'Huntsville Municipal': '+4',
    'Iberia Municipal Court': '8Q',
    'Independence Criminal/Traffic': 'IN',
    'Indian Point Village Municipal': '?2',
    'Innsbrook Municipal': '3I',
    'Irondale Municipal': '!W',
    'Ironton Municipal': '2E',
    'Jamesport Municipal': '?9',
    'Jamestown Municipal': '[5',
    'Jasper Municipal': ']K',
    'Jefferson Circuit Court': 'JE',
    'Jefferson City Muni': 'T7',
    'Jefferson County Municipal': 'FF',
    'Jennings Municipal': ']4',
    'Jerico Springs Municipal': ']E',
    'Jonesburg Municipal Court': '[O',
    'Joplin Municipal': 'O2',
    'Juvenile Office Caldwell': 'DL',
    'Juvenile Office Clinton': 'LT',
    'Juvenile Office Daviess': 'VJ',
    'Juvenile Office DeKalb': 'KJ',
    'Juvenile Office Livingston': 'LS',
    'Juvenile Office Perry': 'PY',
    'Kahoka Municipal': ')I',
    'Kansas City Criminal/Traffic': 'KT',
    'Kelso Municipal Court': ']R',
    'Kennett Municipal Court': 'D=',
    'Kidder Municipal': '?A',
    'Kimberling City Municipal': '39',
    'King City Municipal': '72',
    'Kingsville Municipal': '*N',
    'Kinloch Municipal': '+N',
    'Kirksville Municipal Court': '9Q',
    'Kirkwood Municipal Court': '26',
    'Knob Noster Municipal': '6A',
    'Koshkonong Municipal': '?O',
    'La Monte Municipal': 'GW',
    'Laclede Circuit': 'LA',
    'Laddonia Municipal Court': '[8',
    'Ladue Municipal Court': '36',
    'Lafayette Hall': 'LH',
    'Lagrange Municipal': '3J',
    'Lake Annette Municipal': '*P',
    'Lake Lafayette Municipal': '+5',
    'Lake Lotawana Municipal Court': '2T',
    'Lake Ozark Municipal': 'LZ',
    'Lake St. Louis Municipal': 'L5',
    'Lake Tapawingo Municipal': '5V',
    'Lake Waukomis Municipal': '9P',
    'Lakeshire Municipal': '+P',
    'Lamar Municipal': '8D',
    'Lanagan Municipal Court': ')7',
    'Lancaster Municipal': 'J:',
    'Laplata Municipal': '2F',
    'Laurie Municipal': '5G',
    'Lawrence': 'LW',
    'Leadington Municipal': '9M',
    'Leadwood Municipal': '32',
    'Leasburg Municipal': '[4',
    'Lebanon Municipal Court': '$6',
    "Lee's Summit Municipal Court": '33',
    'Leeton Municipal': '*Q',
    'Liberal Municipal Court': ']D',
    'Licking Municipal': '8V',
    'Lilbourn Municipal': '(Q',
    'Lincoln Municipal': 'L1',
    'Linn Creek Municipal Court': '2=',
    'Linn Municipal': 'A:',
    'Livingston Circuit Court': 'LV',
    'Lockwood Municipal Court': ']G',
    'Lone Jack Municipal': 'L9',
    'Louisiana Municipal Court': '$B',
    'Lowry City Municipal': 'C:',
    'Macon Municipal Court': '4V',
    'Madison Municipal': '*9',
    'Maitland Municipal': '!3',
    'Malden Municipal': '4H',
    'Manchester Municipal': ']5',
    'Mansfield Municipal': '9D',
    'Maplewood Municipal Court': 'Q2',
    'Marble Hill Municipal': '(A',
    'Marceline Municipal': '4W',
    'Maries Associate': 'M4',
    'Maries Circuit': 'MS',
    'Marion Hannibal': 'MR',
    'Marion Palmyra': 'MM',
    'Marionville Municipal': '92',
    'Marquand Municipal': 'B:',
    'Marshall Municipal': '3K',
    'Marshfield Municipal Court': '24',
    'Marston Municipal': '97',
    'Marthasville Municipal': '!U',
    'Martinsburg Municipal Division': '?Z',
    'Maryland Heights Municipal': ']7',
    'Maryville Municipal Court': '8F',
    'Matthews Municipal': 'MH',
    'Maysville Municipal': '?C',
    'Mayview Municipal': '!H',
    'McDonald': 'MC',
    'Memphis Municipal': 'O=',
    'Mercer Municipal': ']Z',
    'Merriam Woods Municipal': '8T',
    'Mexico Municipal Court': '$H',
    'Middleton Municipal Court': '+2',
    'Milan Municipal': '!T',
    'Miller Circuit': 'ML',
    'Miller Municipal Court': '3X',
    'Miner Municipal Court': '(E',
    'Miramiguoa Park Municipal': '5O',
    'Missouri City Municipal': ')O',
    'Moberly Municipal Court': '6R',
    'Moline Acres Municipal': '7F',
    'Monett Municipal': 'MQ',
    'Moniteau Circuit': 'MT',
    'Monroe City Municipal': '2K',
    'Montgomery Municipal Court': '6C',
    'Montrose Municipal': '!M',
    'Morehouse Municipal Court': '6B',
    'Morgan': 'MG',
    'Morley Municipal Court': '(F',
    'Mosby Municipal': '7V',
    'Moscow Mills Municipal': '49',
    'Mound City Municipal': '*3',
    'Moundville Municipal': 'BG',
    'Mount Vernon Municipal': 'MV',
    'Mountain Grove Municipal': '5P',
    'Napoleon Municipal': '+6',
    'Naylor Municipal Court': '*Y',
    'Neosho Municipal Court': '5H',
    'Nevada Municipal': 'NV',
    'New Bloomfield Municipal': '25',
    'New Florence Municipal Court': 'A5',
    'New Franklin Municipal': '4I',
    'New Hampton Municipal': ']Y',
    'New Haven Municipal Court': '3A',
    'New London Municipal': '*A',
    'New Madrid Municipal Court': '4K',
    'Newburg Municipal': '+Y',
    'Newton': 'NW',
    'Nianqua Municipal': ']N',
    'Nixa Municipal Court': '6V',
    'Noel Municipal Court': '2G',
    'Norborne Municipal': '!D',
    'Normandy Municipal': '46',
    'North Kansas City Municipal': 'KS',
    'Northmoor Muni': 'N4',
    'Northmoor Municipal': 'U6',
    'Northwoods Municipal Court': ']8',
    'Novinger Municipal': '!S',
    "O'Fallon Municipal": 'OF',
    'Oakland Municipal': '77',
    'Odessa Municipal Court': '8S',
    'Old Monroe Municipal': '4N',
    'Olivette Municipal Court': '48',
    'Oran Municipal Court': ']S',
    'Oregon Municipal': '!4',
    'Oronogo Municipal Court': 'E=',
    'Osborn Municipal': '?D',
    'Osceola Municipal': 'D:',
    'Otterville Municipal': 'AX',
    'Overland Municipal': '7L',
    'Owensville Municipal': '5M',
    'Ozark Circuit Court': 'OZ',
    'Ozark Municipal': '29',
    'PINE LAWN MUNICIPAL COURT': '+Q',
    'Pacific Municipal': '65',
    'Pagedale Municipal Court': '76',
    'Palmyra Municipal': '9G',
    'Paris Municipal': '*B',
    'Park Hills Municipal': '58',
    'Parma Municipal Court': '(S',
    'Parnell Municipal': 'NN',
    'Pasadena Hills Municipal': '2B',
    'Pasadena Park Municipal': '@C',
    'Pattonsburg Municipal': '!P',
    'Pemiscot County Justice Center': 'PM',
    'Perry Municipal': '*C',
    'Perryville Municipal': '4A',
    'Pevely Municipal': 'PV',
    'Phelps Circuit': 'PH',
    'Pickering Municipal': '!6',
    'Piedmont Municipal Court': '6H',
    'Pierce City Municipal': 'PC',
    'Pilot Grove Municipal Division': '7O',
    'Pilot Knob Municipal Court': '4E',
    'Pineville Municipal Court': ')8',
    'Platte City Municipal': '2Z',
    'Pleasant Hill Municipal': '55',
    'Pleasant Hope Municipal': '*I',
    'Polo Municipal': '3Y',
    'Portageville Municipal Court': '6E',
    'Potosi Municipal': '7Z',
    'Praethersville Municipal': ')P',
    'Prairie Home Municipal': '4O',
    'Princeton Municipal': '?M',
    'Probate (Independence)': 'P9',
    'Probate (Kansas City)': 'P8',
    'Probate Division': 'F8',
    'Probate Division III': 'D3',
    'Probate St Louis County': 'PS',
    'Pulaski Circuit': 'PU',
    'Purcell Municipal': '[3',
    'Purdy Municipal': 'PD',
    'Queen City Municipal': '*O',
    'Quitman Municipal': 'NO',
    'Qulin Municipal Division': '*Z',
    'Ralls Circuit Court': 'RL',
    'Ravenwood Municipal': 'NP',
    'Raytown Municipal': '82',
    'Reeds Springs Municipal': '5L',
    'Republic Municipal': '23',
    'Rhineland Municipal': '7:',
    'Rich Hill Municipal': '7P',
    'Richland Municipal Court': '8U',
    'Richmond Heights Municipal': '56',
    'Ridgeway Municipal': 'RW',
    'Risco Municipal': '5N',
    'Riverview Municipal Court': ']9',
    'Rock Hill Municipal Court': ']A',
    'Rock Port Municipal': '8M',
    'Rockaway Beach Muni': 'Q=',
    'Rogersville Municipal Court': '59',
    'Rolla Municipal Court': 'K=',
    'Rosebud Municipal': '7I',
    'Rush Hill Municipal Court': '[9',
    'Salem Municipal': '[6',
    'Sarcoxie Municipal': '(9',
    'Savannah Municipal': '!8',
    'Scotts City Municipal': '$8',
    'Sedalia Municipal Court': ')Y',
    'Seligman Municipal Court': 'S=',
    'Senath Municipal': '8N',
    'Seneca Municipal Court': ')9',
    'Seymour Muni': 'O1',
    'Shelbina Municipal': '3L',
    'Shelbyville Municipal': 'BM',
    'Sheldon Municipal Court': ']I',
    'Shrewsbury Municipal': '5=',
    'Silex Municipal': '!Z',
    'Skidmore Municipal': '*4',
    'Slater Municipal': '2R',
    'Smithton Municipal': '9C',
    'Smithville Municipal': 'T=',
    'South Central Correctional CR': 'T2',
    'South Gifford Macon': 'GS',
    'Southwest City Municipal Court': '6D',
    'Sparta Municipal Division': '3T',
    'Springfield Municipal': '7M',
    'St Ann Municipal Court': '4=',
    'St Charles City Municipal': 'CZ',
    'St Clair Municipal Court': '+G',
    'St James Municipal': '3B',
    'St Louis Co Municipal': 'S6',
    'St Louis County': 'SL',
    'St Robert Municipal': 'L=',
    'St. Charles County Municipal Court': '@4',
    'St. John Municipal': '7=',
    'St. Louis City Municipal': 'S2',
    'St. Mary Municipal': '3G',
    'St. Peters Municipal': 'PZ',
    'St.Clair County Circuit Court': 'SR',
    'Stafford Municipal Court': '5W',
    'Stanberry Municipal': '2Y',
    'Ste. Genevieve Municipal': '3W',
    'Steele Municipal Court': '(T',
    'Steelville Municipal Court': '2I',
    'Stewarsville Municipal': '?E',
    'Stockton Municipal Court': '4L',
    'Stone': 'SN',
    'Stotts City Municipal Court': ']X',
    'Stover Municipal': '9A',
    'Strasburg Municipal': '*R',
    'Sturgeon Municipal Division': '3C',
    'Sullivan Municipal': 'SI',
    'Summersville Municipal': 'SM',
    'Sunrise Beach Municipal Court': '4G',
    'Sunset Hills Municipal Court': '8L',
    'Sycamore Hills Municipal': '8=',
    'Taos Municipal': '8:',
    'Tarkio Municipal Court': '2Q',
    'Texas Associate': 'X1',
    'Texas Circuit': 'TE',
    'Theodosia Municipal Court': ')K',
    'Tina Municipal': '?W',
    'Tipton Municipal': '5F',
    'Town and Country Municipal': '96',
    'Tracy Municipal Court': '6Y',
    'Traffic Division': 'B8',
    'Trenton Municipal': '4X',
    'Trimble Municipal': 'TM',
    'Truesdale Municipal': '!V',
    'Truxton Municipal': '2:',
    'Union Municipal Court': '[K',
    'Unionstar Municipal': '?F',
    'Unionville Municipal': '8H',
    'University City Municipal': '86',
    'Uplands Park Municipal': '66',
    'Urbana Municipal': 'UB',
    'Urich Municipal': '9I',
    'Valley Park Municipal': 'V2',
    'Van Buren Municipal': ')X',
    'Vandalia Municipal Court': '3N',
    'Vandiver Village Audrain': 'VV',
    'Velda City Municipal': '28',
    'Velda Village Hills Municipal': '38',
    'Verona Municipal': ')2',
    'Viburnum Municipal Court': ')E',
    'Vienna Municipal': '*T',
    'Village of Westwood Municipal': 'WW',
    'Vinita Park Municipal Court': '89',
    'Walker Municipal Court': ']J',
    'Walnut Grove Municipal': '*V',
    'Wardsville Municipal': '9:',
    'Warrenton Municipal': 'WN',
    'Warsaw Municipal Court': '7T',
    'Warson Woods Municipal': '67',
    'Washburn Municipal': 'WH',
    'Waverly Municipal': '22',
    'Waynesville Municipal': '4S',
    'Webb City Municipal': 'WC',
    'Webster Groves Municipal Court': '3=',
    'Weldon Spring Municipal': '7H',
    'Wellington Municipal': '+8',
    'Wellston Municipal Division': '+R',
    'Wellsville Municipal': '8P',
    'Wentzville Municipal': 'WZ',
    'Weston Municipal Court': '6T',
    'Wheaton Municipal': ')4',
    'Wildwood Municipal Court': ']B',
    'Willard Municipal Court': '7S',
    'Williamsville Municipal': ')F',
    'Winchester Municipal': '5C',
    'Windsor Municipal': 'I=',
    'Windsor Place Municipal': '6I',
    'Winfield Municipal': 'WF',
    'Winona Municipal': '5D',
    'Winston Municipal': '?H',
    'Wood Heights Municipal': '9Y',
    'Woodson Terrace Municipal': '+T',
    'Wright Circuit Court': 'WR',
    'Wright City Municipal': ')L'
}

COUNTY_LOCATIONS = {
    'Adair': ['Novinger Municipal',
            'Kirksville Municipal Court',
            'Circuit Division',
            'Brashear Municipal',
            'Associate Division Adair'],
    'Andrew': ['Country Club Municipal',
            'Savannah Municipal',
            'Circuit Division',
            'Associate Division'],
    'Atchison': ['Tarkio Municipal Court',
                'Rock Port Municipal',
                'Fairfax Municipal',
                'Circuit Division',
                'Associate Division'],
    'Audrain': ['Mexico Municipal Court',
                'Vandalia Municipal Court',
                'Benton City Municipal Court',
                'Martinsburg Municipal Division',
                'Circuit Division Audrain',
                'Associate Division Audrain',
                'Vandiver Village Audrain',
                'Farber Municipal Court',
                'Laddonia Municipal Court',
                'Rush Hill Municipal Court'],
    'Barry': ['Wheaton Municipal',
            'Exeter Municipal',
            'Cassville Municipal Court',
            'Barry',
            'Butterfield Municipal',
            'Monett Municipal',
            'Purdy Municipal',
            'Associate Division Barry',
            'Seligman Municipal Court',
            'Washburn Municipal'],
    'Barton': ['Lamar Municipal',
            'Associate Division',
            'Golden City Municipal',
            'Liberal Municipal Court'],
    'Bates': ['Adrain Municipal',
            'Tipton Municipal',
            'Rich Hill Municipal',
            'Bates County Circuit Court',
            'Associate Div Bates'],
    'Benton': ['Cole Camp Municipal',
            'Warsaw Municipal Court',
            'Associate/Circuit Divisions',
            'Lincoln Municipal'],
    'Bollinger': ['Marble Hill Municipal',
                'Circuit Division',
                'Associate Division'],
    'Boone': ['Sturgeon Municipal Division',
            'Hallsville Municipal Division',
            'Columbia Municipal',
            'Probate Division',
            'Circuit Division',
            'Ashland Municipal Division',
            'Centralia Municipal Division'],
    'Buchanan': ['Circuit Division', 'Easton Buchanan Municipal'],
    'Butler': ['Fisk Municipal Division',
            'Qulin Municipal Division',
            'Associate/Circuit Divisions'],
    'Caldwell': ['Caldwell Municipal',
                'Polo Municipal',
                'Braymer Municipal',
                'Breckenridge Municipal',
                'Cowgill Municipal',
                'Kidder Municipal',
                'Caldwell Circuit Court',
                'Juvenile Office Caldwell'],
    'Callaway': ['New Bloomfield Municipal',
                'Auxvasse Municipal',
                'Fulton Municipal Court',
                'Holts Summit Municipal Court',
                'Circuit Division'],
    'Camden': ['Linn Creek Municipal Court',
            'Sunrise Beach Municipal Court',
            'Camdenton Municipal',
            'Four Seasons Municipal Court',
            'Camden Circuit'],
    'Cape Girardeau': ['Perryville Municipal',
                    'Circuit Division (Cape Girard)',
                    'Circuit Division (Jackson)',
                    'Associate Probate Division',
                    'Associate Division (Jackson)',
                    'Gordonville Municipal',
                    'Allenville Municipal',
                    'Delta Municipal'],
    'Carroll': ['Bogard Municipal',
                'Bosworth Municipal',
                'Hale Municipal',
                'Norborne Municipal',
                'Carrollton Municipal',
                'Tina Municipal',
                'Circuit Division',
                'Associate Division'],
    'Carter': ['Ellsinore Municipal',
            'Grandin Municipal',
            'Van Buren Municipal',
            'Circuit Division',
            'Associate Division'],
    'Cass': ['Archie Municipal',
            'Cleveland Municipal',
            'Creighton Municipal',
            'Drexel Municipal',
            'East Lynne Municipal',
            'Freeman Municipal',
            'Lake Annette Municipal',
            'Strasburg Municipal',
            'Garden City Municipal',
            'Pleasant Hill Municipal',
            'Cass County Ordinance Court',
            'Cass Circuit',
            'Probate Division'],
    'Cedar': ['Stockton Municipal Court',
            'Circuit Division',
            'El Dorado Springs Municipal',
            'Jerico Springs Municipal'],
    'Chariton': ['Circuit Division', 'Associate Division'],
    'Christian': ['Ozark Municipal',
                'Sparta Municipal Division',
                'City of Billings Municipal Court',
                'Nixa Municipal Court',
                'City of Clever Municipal Court',
                'Christian Historic Courthouse',
                'Circuit Division',
                'Christian County Cir Ct Bldg',
                'Highlandville Municipal',
                'Associate Civil Div Christian',
                'Assoc Crim/Probate Christian'],
    'Clark': ['Kahoka Municipal', 'Circuit Division', 'Associate Division'],
    'Clay': ['Missouri City Municipal',
            'Praethersville Municipal',
            'Avondale Municipal',
            'Birmingham Municipal',
            'Glenaire Municipal',
            'Holt Municipal',
            'Mosby Municipal',
            'Clay Circuit Court',
            'North Kansas City Municipal',
            'Smithville Municipal'],
    'Clinton': ['Cameron Municipal Court',
                'Clinton Circuit Court',
                'Juvenile Office Clinton',
                'Trimble Municipal'],
    'Cole': ['Taos Municipal',
            'Wardsville Municipal',
            'Circuit Division',
            'Probate Division',
            'Associate Division',
            'Jefferson City Muni'],
    'Cooper': ['Boonville Municipal Division',
            'Prairie Home Municipal',
            'Windsor Place Municipal',
            'Pilot Grove Municipal Division',
            'Otterville Municipal',
            'Bunceton Municipal',
            'Blackwater Municipal',
            'Circuit Division',
            'Associate Division'],
    'Crawford': ['Bourbon Municipal Court',
                'Steelville Municipal Court',
                'Associate Division',
                'Circuit Division',
                'Leasburg Municipal'],
    'Dade': ['Circuit Division',
            'Greenfield Municipal',
            'Everton Municipal Court',
            'Lockwood Municipal Court'],
    'Dallas': ['Circuit Division',
            'Associate Division',
            'Urbana Municipal',
            'Buffalo Municipal'],
    'Daviess': ['Gallatin Municipal',
                'Altamont Municipal',
                'Pattonsburg Municipal',
                'Jamesport Municipal',
                'Winston Municipal',
                'Daviess Circuit Court',
                'Associate Division Daviess',
                'Juvenile Office Daviess'],
    'DeKalb': ['Clarksdale Municipal',
            'Maysville Municipal',
            'Osborn Municipal',
            'Stewarsville Municipal',
            'Unionstar Municipal',
            'DeKalb Circuit Court',
            'Associate Division DeKalb',
            'Juvenile Office DeKalb'],
    'Dent': ['Associate Division',
            'Circuit Division',
            'Dent Judicial Building',
            'Salem Municipal'],
    'Douglas': ['Ava Municipal',
                'Douglas Circuit Court',
                'Associate Division Douglas'],
    'Dunklin': ['Hornersville Municipal',
                'Arbyrd Municipal',
                'Malden Municipal',
                'Campbell Municipal',
                'Senath Municipal',
                'Kennett Municipal Court',
                'Circuit Division',
                'Associate Division',
                'Probate Division'],
    'Franklin': ['Gerald Municipal Court',
                'St Clair Municipal Court',
                'New Haven Municipal Court',
                'Miramiguoa Park Municipal',
                'Pacific Municipal',
                'Circuit Division',
                'Associate Division VII',
                'Probate Division',
                'Associate Division VI',
                'Franklin Co Municipal',
                'Sullivan Municipal',
                'Union Municipal Court',
                'City of Washington'],
    'Gasconade': ['Gasconade Municipal Court',
                'Berger Municipal Court',
                'Hermann Municipal',
                'Owensville Municipal',
                'Rosebud Municipal',
                'Bland Municipal',
                'Associate Division',
                'Circuit Division'],
    'Gentry': ['Stanberry Municipal',
            'Albany Municipal',
            'King City Municipal',
            'Circuit Division',
            'Associate Division'],
    'Greene': ['Walnut Grove Municipal',
            'Republic Municipal',
            'Ash Grove Municipal',
            'Fair Grove Municipal Court',
            'Stafford Municipal Court',
            'Battlefield Municipal',
            'Springfield Municipal',
            'Willard Municipal Court',
            'Greene County Ordinance Court',
            'Circuit Division'],
    'Grundy': ['Trenton Municipal', 'Circuit Division', 'Associate Division'],
    'Harrison': ['Gilman City Municipal',
                'Bethany Municipal',
                'Circuit Division',
                'Eagleville Municipal',
                'Ridgeway Municipal',
                'New Hampton Municipal'],
    'Henry': ['Calhoun Municipal',
            'Deepwater Municipal',
            'Montrose Municipal',
            'Urich Municipal',
            'Henry County Circuit Court',
            'Windsor Municipal'],
    'Hickory': ['Associate Division', 'Circuit Division'],
    'Holt': ['Big Lake Municipal',
            'Maitland Municipal',
            'Oregon Municipal',
            'Forest City Municipal',
            'Mound City Municipal',
            'Craig Municipal',
            'Circuit Division',
            'Associate Division'],
    'Howard': ['New Franklin Municipal',
            'Fayette Municipal',
            'Glasgow Municipal',
            'Associate Division',
            'Circuit Division'],
    'Howell': ['Circuit Division', 'Associate Division'],
    'Iron': ['Viburnum Municipal Court',
            'Ironton Municipal',
            'Pilot Knob Municipal Court',
            'Arcadia Municipal',
            'Associate Division',
            'Annapolis Municipal',
            'Circuit Division'],
    'Jackson': ['Lake Lotawana Municipal Court',
                "Lee's Summit Municipal Court",
                'Lake Tapawingo Municipal',
                'Grandview Municipal',
                'Raytown Municipal',
                'Greenwood Municipal',
                'Circuit Division (Family Ct Justice Cntr)',
                'Circuit Division (Kansas City)',
                'Circuit Division (Independence)',
                'Criminal Justice Center',
                'Independence Criminal/Traffic',
                'Kansas City Criminal/Traffic',
                'Lone Jack Municipal',
                'Probate (Kansas City)',
                'Probate (Independence)'],
    'Jasper': ['Carterville Municipal',
            'Sarcoxie Municipal',
            'Circuit Division (Joplin)',
            'Circuit Division (Carthage)',
            'Carthage Municipal',
            'Probate Division III',
            'Associate Division IV',
            'Associate Division V',
            'Duquesne Municipal',
            'Oronogo Municipal Court',
            'Joplin Municipal',
            'Carl Junction Municipal',
            'Webb City Municipal',
            'Purcell Municipal',
            'Jasper Municipal',
            'Airport Drive Municipal'],
    'Jefferson': ['Byrnes Municipal',
                'Crystal City Municipal',
                'Arnold Municipal',
                'Herculaneum Municipal',
                'Desoto Municipal',
                'Festus Municipal',
                'Jefferson County Municipal',
                'Hillsboro Municipal',
                'Jefferson Circuit Court',
                'Pevely Municipal'],
    'Johnson': ['Centerview Muncipal',
                'Chilhowee Municipal',
                'Holden Municipal',
                'Kingsville Municipal',
                'Leeton Municipal',
                'Knob Noster Municipal',
                'Circuit Division',
                'Associate Division',
                'Probate Division'],
    'Knox': ['Edina Municipal', 'Associate Division Knox', 'Circuit Division'],
    'Laclede': ['Lebanon Municipal Court', 'Conway Municipal', 'Laclede Circuit'],
    'Lafayette': ['Corder Municipal',
                'Mayview Municipal',
                'Emma Municipal',
                'Lake Lafayette Municipal',
                'Napoleon Municipal',
                'Wellington Municipal',
                'Waverly Municipal',
                'Concordia Municipal',
                'Odessa Municipal Court',
                'Higginsville Municipal Court',
                'Alma Municipal',
                'Associate Division',
                'Probate Division',
                'Circuit Division',
                'Lafayette Hall',
                'Bates City Municipal'],
    'Lawrence': ['Verona Municipal',
                'Miller Municipal Court',
                'Aurora Municipal Court',
                'Marionville Municipal',
                'Associate Division Lawrence',
                'Lawrence',
                'Mount Vernon Municipal',
                'Pierce City Municipal',
                'Freistatt Municipal Court',
                'Stotts City Municipal Court'],
    'Lewis': ['Canton Municipal', 'Lagrange Municipal', 'Circuit Division'],
    'Lincoln': ['Silex Municipal',
                'Truxton Municipal',
                'Elsberry Municipal',
                'Moscow Mills Municipal',
                'Old Monroe Municipal',
                'Foley Municipal',
                "Fountain N' Lakes",
                'Hawk Point Municipal',
                'Associate/Circuit Divisions',
                'Winfield Municipal'],
    'Linn': ['Browning Municipal',
            'Bucklin Municipal',
            'Marceline Municipal',
            'Brookfield Municipal',
            'Circuit Division'],
    'Livingston': ['Chillicothe Municipal',
                'Associate Division Livingston',
                'Juvenile Office Livingston',
                'Livingston Circuit Court'],
    'Macon': ['Callao Municipal',
            'Laplata Municipal',
            'Macon Municipal Court',
            'Bevier Municipal',
            'South Gifford Macon',
            'Associate Division',
            'Circuit Division',
            'Atlanta Municipal'],
    'Madison': ['Fredericktown Municipal',
                'Marquand Municipal',
                'Associate Division',
                'Circuit Division'],
    'Maries County': ['Vienna Municipal',
                    'Belle Municipal',
                    'Maries Associate',
                    'Maries Circuit'],
    'Marion': ['Hannibal Municipal Court',
            'Palmyra Municipal',
            'Marion Palmyra',
            'Marion Hannibal'],
    'McDonald': ['Lanagan Municipal Court',
                'Pineville Municipal Court',
                'Anderson Municipal Court',
                'Noel Municipal Court',
                'Goodman Municipal Court',
                'Southwest City Municipal Court',
                'McDonald'],
    'Mercer': ['Princeton Municipal',
            'Circuit Division',
            'Associate Division',
            'Mercer Municipal'],
    'Miller': ['Eldon Municipal Court',
            'Iberia Municipal Court',
            'Lake Ozark Municipal',
            'Miller Circuit'],
    'Mississippi': ['Circuit Division', 'Anniston Municipal Court'],
    'Moniteau': ['California Municipal Court',
                'Clarksburg Municipal Court',
                'Tipton Municipal',
                'Associate Division Moniteau',
                'Moniteau Circuit',
                'Jamestown Municipal'],
    'Monroe': ['Madison Municipal',
            'Paris Municipal',
            'Monroe City Municipal',
            'Circuit Division'],
    'Montgomery': ['Middleton Municipal Court',
                'Montgomery Municipal Court',
                'Rhineland Municipal',
                'Wellsville Municipal',
                'Associate Division',
                'Bellflower Municipal Court',
                'New Florence Municipal Court',
                'Circuit Division',
                'High Hill Municipal Court',
                'Jonesburg Municipal Court'],
    'Morgan': ['Laurie Municipal',
            'Stover Municipal',
            'Associate Division Morgan',
            'Morgan'],
    'New Madrid': ['Lilbourn Municipal',
                'Parma Municipal Court',
                'New Madrid Municipal Court',
                'Risco Municipal',
                'Morehouse Municipal Court',
                'Portageville Municipal Court',
                'Marston Municipal',
                'Associate Division',
                'Canalou Municipal',
                'Matthews Municipal',
                'Circuit Division'],
    'Newton': ['Diamond Municipal Court',
            'Granby Municipal Court',
            'Seneca Municipal Court',
            'Neosho Municipal Court',
            'Fairview Municipal',
            'Newton'],
    'Nodaway': ['Hopkins Municipal',
                'Pickering Municipal',
                'Skidmore Municipal',
                'Maryville Municipal Court',
                'Burlington Junction Municipal',
                'Clearmont Municipal',
                'Clyde Municipal',
                'Circuit Division',
                'Conception Junction Municipal',
                'Conception Municipal',
                'Elmo Municipal',
                'Graham Municipal',
                'Guilford Municipal',
                'Parnell Municipal',
                'Quitman Municipal',
                'Ravenwood Municipal',
                'Barnard Municipal'],
    'Oregon': ['Alton Municipal',
            'Koshkonong Municipal',
            'Circuit Division',
            'Associate Division'],
    'Osage': ['Linn Municipal',
            'Associate Division',
            'Circuit Division',
            'Freeburg Municipal'],
    'Ozark': ['Gainsville Municipal Court',
            'Theodosia Municipal Court',
            'Associate Division Ozark',
            'Ozark Circuit Court'],
    'Pemiscot': ['Caruthersville Municipal Court',
                'Steele Municipal Court',
                'Associate Division',
                'Probate Division',
                'Circuit Division',
                'Pemiscot County Justice Center'],
    'Perry': ['Associate Division', 'Circuit Division', 'Juvenile Office Perry'],
    'Pettis': ['Greenridge Municipal',
            'Sedalia Municipal Court',
            'Smithton Municipal',
            'Houstonia Municipal',
            'Hughesville Municipal',
            'Associate Division',
            'Probate Division',
            'La Monte Municipal',
            'Circuit Division'],
    'Phelps County': ['Edgar Springs Municipal',
                    'Newburg Municipal',
                    'St James Municipal',
                    'Doolittle Municipal',
                    'Rolla Municipal Court',
                    'Phelps Circuit'],
    'Pike': ['Louisiana Municipal Court',
            'Eolia Municipal',
            'Clarksville Municipal',
            'Frankford Municipal',
            'Bowling Green Municipal',
            'Associate Division',
            'Circuit Division'],
    'Platte': ['Dearborn Municipal',
            'Platte City Municipal',
            'Weston Municipal Court',
            'Tracy Municipal Court',
            'Ferrelview Municipal',
            'Lake Waukomis Municipal',
            'Camden Point Municipal',
            'Edgerton Municipal',
            'Houston Lake Municipal',
            'Circuit Division',
            'Northmoor Muni',
            'Northmoor Municipal'],
    'Polk': ['Pleasant Hope Municipal',
            'Bolivar Municipal',
            'Associate Division',
            'Humansville Municipal',
            'Circuit Division'],
    'Pulaski': ['Waynesville Municipal',
                'Dixon Municipal',
                'Crocker Municipal',
                'Richland Municipal Court',
                'St Robert Municipal',
                'Pulaski Circuit'],
    'Putnam': ['Unionville Municipal', 'Circuit Division', 'Associate Division'],
    'Ralls': ['Center Municipal',
            'New London Municipal',
            'Perry Municipal',
            'Ralls Circuit Court'],
    'Randolph': ['Huntsville Municipal',
                'Clark Municipal',
                'Moberly Municipal Court',
                'Associate/Circuit Divisions'],
    'Ray': ['Crystal Lakes Municipal',
            'Homestead Municipal',
            'Wood Heights Municipal',
            'Fleming Municipal',
            'Hardin Municipal',
            'Henrietta Municipal',
            'Associate Division',
            'Camden Municipal',
            'Crystal Lakes Municipal',
            'Circuit Division'],
    'Reynolds': ['Bunker Municipal Court',
                'Ellington Municipal Court',
                'Associate Division',
                'Circuit Division'],
    'Ripley': ['Doniphan Municipal Court',
            'Naylor Municipal Court',
            'Associate/Circuit Divisions'],
    'Saline': ['Blackburn Municipal',
            'Slater Municipal',
            'Marshall Municipal',
            'Associate Division',
            'Probate Division',
            'Circuit Division'],
    'Schuyler': ['Queen City Municipal',
                'Greentop Municipal',
                'Associate Division',
                'Lancaster Municipal',
                'Circuit Division'],
    'Scotland': ['Associate Division', 'Memphis Municipal', 'Circuit Division'],
    'Scott': ['Scotts City Municipal',
            'Miner Municipal Court',
            'Morley Municipal Court',
            'Associate Division',
            'Probate Division',
            'Circuit Division',
            'Benton Municipal Court',
            'Kelso Municipal Court',
            'Oran Municipal Court'],
    'Shannon': ['Eminence Municipal',
                'Winona Municipal',
                'Birch Tree Municipal',
                'Circuit Division',
                'Associate Division'],
    'Shelby': ['Shelbina Municipal',
            'Clarence Municipal',
            'Shelbyville Municipal',
            'Associate Division',
            'Circuit Division'],
    'St. Charles': ['Weldon Spring Municipal',
                    'St. Charles County Municipal Court',
                    'Circuit Division',
                    'Traffic Division',
                    'Associate Civil/Small Claim',
                    'St Charles City Municipal',
                    'Dardenne Prarie Municipal',
                    'Probate Division',
                    'Criminal Associate Division',
                    'Foristell Municipal',
                    'Lake St. Louis Municipal',
                    "O'Fallon Municipal",
                    'Cottleville Municipal',
                    'St. Peters Municipal',
                    'Augusta Municipal',
                    'Wentzville Municipal'],
    'St. Clair': ['Appleton City Municipal',
                'Lowry City Municipal',
                'Osceola Municipal',
                'St.Clair County Circuit Court'],
    'St. Francois': ['Leadwood Municipal',
                    'Farmington Municipal',
                    'Park Hills Municipal',
                    'Bonne Terre Municipal Court',
                    'Leadington Municipal',
                    'Desloge Municipal',
                    'Associate Division 3',
                    'Probate Division',
                    'Circuit Division'],
    'St. Louis County': ['Bellerive Acres Municipal',
                        'Crystal Lake Park Municipal',
                        'Frontenac Municipal Court',
                        'Greendale Municipal',
                        'Hillsdale Municipal',
                        'Kinloch Municipal',
                        'Lakeshire Municipal',
                        'PINE LAWN MUNICIPAL COURT',
                        'Wellston Municipal Division',
                        'Woodson Terrace Municipal',
                        'Kirkwood Municipal Court',
                        'Crestwood Municipal',
                        'Velda City Municipal',
                        'Pasadena Hills Municipal',
                        'Ladue Municipal Court',
                        'Brentwood Municipal',
                        'Velda Village Hills Municipal',
                        'Webster Groves Municipal Court',
                        'Normandy Municipal',
                        'Clayton Municipal Court',
                        'Olivette Municipal Court',
                        'St Ann Municipal Court',
                        'Richmond Heights Municipal',
                        'Shrewsbury Municipal',
                        'Winchester Municipal',
                        'Country Club Hills',
                        'Bridgeton Municipal',
                        'Uplands Park Municipal',
                        'Warson Woods Municipal',
                        'Champ Municipal',
                        'Ballwin Municipal',
                        'Pagedale Municipal Court',
                        'Oakland Municipal',
                        'Flordell Hills Municipal',
                        'St. John Municipal',
                        'Moline Acres Municipal',
                        'Overland Municipal',
                        'Bellefontaine Neighbors',
                        'University City Municipal',
                        'Clarkson Valley Municipal',
                        'Vinita Park Municipal Court',
                        'Sycamore Hills Municipal',
                        'Grantwood Village Municipal',
                        'Sunset Hills Municipal Court',
                        'Ellisville Municipal Court',
                        'Eureka Municipal',
                        'Town and Country Municipal',
                        'Edmundson Muncipal Court',
                        'Glen Echo Park Municipal',
                        'Bella Villa Municipal Court',
                        'Pasadena Park Municipal',
                        'Beverly Hills Municipal',
                        'Hazelwood Municipal',
                        'Berkeley Municipal',
                        'Creve Coeur Municipal',
                        'Florissant Municipal Court',
                        'Probate St Louis County',
                        'Maplewood Municipal Court',
                        'St Louis Co Municipal',
                        'St Louis County',
                        'Valley Park Municipal',
                        'Village of Westwood Municipal',
                        'Bel-Nor Municipal',
                        'Bel-Ridge Municipal Court',
                        'Black Jack Municipal',
                        'Breckenridge Hills Municipal',
                        'Calverton Park Municipal',
                        'Charlack Municipal Court',
                        'Chesterfield Municipal Court',
                        'Cool Valley Municipal',
                        'Dellwood Municipal',
                        'Des Peres Municipal',
                        'Fenton Municipal',
                        'Ferguson Municipal Court',
                        'Glendale Municipal',
                        'Hanley Hills Municipal Court',
                        'Jennings Municipal',
                        'Manchester Municipal',
                        'Maryland Heights Municipal',
                        'Northwoods Municipal Court',
                        'Riverview Municipal Court',
                        'Rock Hill Municipal Court',
                        'Wildwood Municipal Court'],
    'Ste. Genevieve': ['St. Mary Municipal',
                    'Ste. Genevieve Municipal',
                    'Associate Division',
                    'Circuit Division'],
    'Stoddard': ['Dexter Municipal',
                'Associate Division',
                'Div III & Probate',
                'Circuit Division',
                'Bell City Municipal',
                'Essex Municipal'],
    'Stone': ['Kimberling City Municipal',
            'Branson West Municipal',
            'Crane Municipal Court',
            'Reeds Springs Municipal',
            'Galena Municipal',
            'Indian Point Village Municipal',
            'Stone'],
    'Sulivan': ['Milan Municipal', 'Green City Municipal', 'Circuit Division'],
    'Taney': ['Forsyth Municipal',
            'Branson Municipal',
            'Merriam Woods Municipal',
            'Circuit Division',
            'Associate Civil Division Taney',
            'Assoc Crim/Probate Div Taney',
            'Rockaway Beach Muni'],
    'Texas': ['Cabool Municipal',
            'Houston Municipal',
            'Licking Municipal',
            'Summersville Municipal',
            'South Central Correctional CR',
            'Texas Circuit',
            'Texas Associate'],
    'The City of St. Louis': ['Carnahan Courthouse',
                            'St. Louis City Municipal',
                            'Probate Division',
                            'City of St. Louis'],
    'Vernon': ['Moundville Municipal',
            'Nevada Municipal',
            'Circuit Division',
            'Bronaugh Municipal Court',
            'Sheldon Municipal Court',
            'Walker Municipal Court'],
    'Warren': ['Marthasville Municipal',
            'Truesdale Municipal',
            'Wright City Municipal',
            'Innsbrook Municipal',
            'Associate Division',
            'Circuit Division',
            'Warrenton Municipal'],
    'Washington': ['Irondale Municipal',
                'Caledonia Municipal',
                'Potosi Municipal',
                'Associate Division',
                'Circuit Division'],
    'Wayne': ['Williamsville Municipal',
            'Piedmont Municipal Court',
            'Associate Division',
            'Circuit Division'],
    'Webster': ['Marshfield Municipal Court',
                'Rogersville Municipal Court',
                'Fordland Municipal',
                'Associate Division',
                'Seymour Muni',
                'Circuit Division',
                'Nianqua Municipal'],
    'Worth': ['Grant City Municipal', 'Associate Division', 'Circuit Division'],
    'Wright': ['Hartville Municipal',
            'Mountain Grove Municipal',
            'Mansfield Municipal',
            'Associate Division Wright',
            'Wright Circuit Court']
}

CASE_TYPE = [
    'Civil',
    'Criminal',
    'Infraction',
    'Probate',
    'Traffic/Municipal'
]

COUNTIES = [
    'Clark',
    'Scotland',
    'Schuyler',
    'Adair',
    'Knox',
    'Lewis',
    'Grundy', 
    'Harrison', 
    'Mercer',
    'Putnam',
    'Atchison',
    'Gentry',
    'Holt',
    'Nodaway',
    'Worth',
    'Andrew',
    'Buchanan',
    'Platte',
    'Clay',
    'Carroll',
    'Ray',
    'Sullivan', 
    'Linn',
    'Chariton',
    'Marion', 
    'Monroe',
    'Ralls',
    'St. Charles',
    'Audrain', 
    'Montgomery',
    'Warren',
    'Boone',
    'Callaway',
    'Randolph',
    'Howard',
    'Saline',
    'Lafayette',
    'Jackson',
    'Cass',
    'Johnson',
    'Cooper',
    'Pettis',
    'Cole',
    'Franklin',
    'Gasconade',
    'Osage',
    'St. Louis',
    'City of St. Louis',
    'Jefferson',
    'Madison',
    'Ste. Genevieve',
    'St.  Francois',
    'Washington',
    'Maries',
    'Phelps',
    'Pulaski',
    'Texas',
    'Camden',
    'Laclede',
    'Miller',
    'Morgan',
    'Moniteau',
    'Bates',
    'Henry',
    'St. Clair',
    'Barton',
    'Cedar',
    'Dade',
    'Vernon',
    'Jasper',
    'Benton',
    'Dallas',
    'Hickory',
    'Polk',
    'Webster',
    'Greene',
    'Bollinger',
    'Cape Girardeau',
    'Perry',
    'Mississippi',
    'Scott',
    'New Madrid',
    'Pemiscot',
    'Dunklin',
    'Stoddard',
    'Butler',
    'Ripley',
    'Carter',
    'Howell',
    'Oregon',
    'Shannon',
    'Christian',
    'Barry',
    'Lawrence',
    'Stone',
    'Newton',
    'McDonald',
    'Macon',
    'Shelby',
    'Dent',
    'Crawford',
    'Iron',
    'Reynolds',
    'Wayne',
    'DeKalb',
    'Daviess',
    'Clinton',
    'Caldwell',
    'Livingston',
    'Douglas',
    'Ozark',
    'Wright',
    'Lincoln',
    'Pike',
    'Taney'
]

CASE_STATUS_INDICES = {
    'All': '0',
    'Pending': '1',
    'Disposed': '2'
}